apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-teste
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: vanbrands/flask:latest
        ports:
        - containerPort: 5000
