name: Docker Package
on:
  push:
    branches:
      - master

jobs:
  package:
    name: Create Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Create docker image
        run: docker build -t docker.pkg.github.com/vanbrands/flask .
